# Generated by Django 3.0.4 on 2020-03-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20200314_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_ingresso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
